-- ── ลบ quotation_salesperson เวอร์ชันเก่า (1 พารามิเตอร์) ทิ้ง ──────────────────────
--
-- 0111 เพิ่มพารามิเตอร์ p_dealer_code เข้าไป โดยใช้ `create or replace function`
-- แต่การเปลี่ยน "จำนวนพารามิเตอร์" = คนละลายเซ็น Postgres จึงสร้างเป็นฟังก์ชันซ้อนอีกตัว
-- ไม่ได้แทนที่ตัวเดิม → เหลืออยู่ 2 ตัวพร้อมกัน
--
-- ผลที่เกิดจริง: เรียกด้วยพารามิเตอร์เดียว PostgREST เลือกไม่ถูกว่าจะใช้ตัวไหน แล้วตอบ
--   PGRST203 "Could not choose the best candidate function" → ช่องผู้รับผิดชอบใบเสนอราคาพัง
--   (จับได้จากเทสต์ regression ทันทีหลัง push · ถ้าไม่มีเทสต์จะไปโผล่ที่หน้าจอผู้ใช้)
--
-- ตัวใหม่รับ p_dealer_code เป็น optional อยู่แล้ว จึงรองรับผู้เรียกแบบเดิมได้ครบ
drop function if exists public.quotation_salesperson(text);
