-- Benjamin PMS — ลูกค้าเป้าหมายของสำนักงานใหญ่ = ผู้สนใจเป็นตัวแทนจำหน่าย (บอสสั่ง 14 ก.ย. 69)
--
-- ══════════════════════════════════════════════════════════════════════════
-- ⚠️ คนละเรื่องกับตาราง leads — ห้ามรวมกัน
--   leads = ลูกค้าที่จะซื้ออาคาร (ของตัวแทนแต่ละสาขา) → ปิดการขายแล้วกลายเป็น "ลูกค้า"
--   ตารางนี้ = คน/บริษัทที่ "สนใจมาเป็นตัวแทน" ของสำนักงานใหญ่ → สำเร็จแล้วกลายเป็น "ตัวแทนจำหน่าย"
--   ถ้าเก็บรวมใน leads: ยอดลูกค้าเป้าหมายทั้งเครือ / อัตราปิดการขาย / กราฟทุกใบบนแดชบอร์ด
--   จะนับผู้สนใจเป็นตัวแทนปนเข้าไปด้วย ตัวเลขผิดทั้งระบบโดยไม่มีใครรู้ตัว
--
-- ช่องข้อมูลตั้งตามไฟล์จริงของเบนจามิน "Dealer BJM PEB" (social · เบอร์ · จังหวัด · ชื่อ ·
--   เริ่มติดต่อ · ติดตาม · Type · หมายเหตุ · Channel) — ไม่เพิ่มช่องที่ไฟล์ไม่มี
-- ขั้นตอน (status) ตั้งตามที่ทีมเขียนไว้ในไฟล์จริง: โทรแล้ว → ส่ง Company Profile → นัดคุย → รอพิจารณา
-- ══════════════════════════════════════════════════════════════════════════

create table if not exists public.dealer_prospects (
  -- by default (ไม่ใช่ always): แอปอัปเดตทั้งแถวรวม id เดิมกลับมา — always จะปฏิเสธทุกการแก้ไข
  id            bigint generated by default as identity primary key,
  name          text not null check (btrim(name) <> ''),
  social        text,          -- ชื่อบนโซเชียล (Facebook/LINE)
  phone         text,
  email         text,
  province      text,
  business_type text,          -- ประเภทธุรกิจ (ผู้รับเหมา / ขายเหล็ก / สถาปนิก …)
  channel       text,          -- ช่องทางที่เข้ามา (FB / LINE OA / LINE PU / Direct)
  first_contact date,          -- เริ่มติดต่อ
  follow_up     date,          -- นัดติดตามครั้งถัดไป
  note          text,
  status        text not null default 'new'
                check (status in ('new', 'contacted', 'profile_sent', 'meeting', 'considering', 'won', 'lost')),
  lost_reason   text,
  assigned      text,          -- ผู้ดูแลฝั่งสำนักงานใหญ่ (ชื่อ ไม่ใช่บัญชีเข้าระบบ)
  -- ตัวแทนที่ผู้สนใจรายนี้กลายมาเป็น
  --   ⚠️ ไม่บังคับ "won ต้องมี dealer_code" ที่ระดับตาราง — ถ้าบังคับ พอลบสาขาทิ้ง (set null)
  --      ฐานข้อมูลจะปฏิเสธการลบสาขานั้นทันทีด้วยข้อความที่ผู้ใช้อ่านไม่รู้เรื่อง
  --      แอป (dealerProspects.ts · ตรวจผู้สนใจ) และ /api/v1/prospects ตรวจกติกานี้แทน
  dealer_code   text references public.dealers(code) on update cascade on delete set null,
  converted_at  timestamptz,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

comment on table public.dealer_prospects is
  'ลูกค้าเป้าหมายของสำนักงานใหญ่ (ผู้สนใจเป็นตัวแทนจำหน่าย) — สำเร็จแล้วผูก dealer_code · คนละเรื่องกับ leads';

create index if not exists dealer_prospects_status_idx on public.dealer_prospects (status);
create index if not exists dealer_prospects_dealer_code_idx on public.dealer_prospects (dealer_code);

-- updated_at ขยับเองทุกครั้งที่แก้ — ไม่พึ่งให้แอปส่งมา (แอปส่งค่าเก่ากลับมาทั้งแถว)
create or replace function public.dealer_prospects_touch() returns trigger
  language plpgsql set search_path = public as $$
begin
  new.updated_at := now();
  return new;
end $$;

drop trigger if exists dealer_prospects_touch on public.dealer_prospects;
create trigger dealer_prospects_touch before update on public.dealer_prospects
  for each row execute function public.dealer_prospects_touch();

-- ── สิทธิ์ ──────────────────────────────────────────────────────────────────────
--   อ่าน  = ฝั่งสำนักงานใหญ่ทุกบทบาท (is_hq)
--   เขียน = ผู้ดูแลข้อมูลกลาง (can_write_master = SUPER_ADMIN / HQ_MANAGEMENT · บัญชีต้องเปิดใช้งาน)
--   ตัวแทนจำหน่ายไม่เห็นสักแถว — รายชื่อผู้สนใจเป็นตัวแทนรายอื่นในพื้นที่เดียวกันเป็นข้อมูลอ่อนไหวทางธุรกิจ
alter table public.dealer_prospects enable row level security;

revoke all on public.dealer_prospects from public, anon;
grant select, insert, update, delete on public.dealer_prospects to authenticated;

drop policy if exists dealer_prospects_read on public.dealer_prospects;
create policy dealer_prospects_read on public.dealer_prospects
  for select using ( is_hq() );

drop policy if exists dealer_prospects_write on public.dealer_prospects;
create policy dealer_prospects_write on public.dealer_prospects
  for all using ( can_write_master() ) with check ( can_write_master() );
