-- Benjamin PMS — ใบเสนอแพ็กเกจตัวแทน (บอสสั่ง 14 ก.ย. 69)
--
-- บอส: "ต้องทำเหมือนดีลเลอร์ที่ต้องมีใบเสนอราคา แต่อันนี้ของ HQ" · "มันคล้ายแฟรนไชส์ แต่ไม่ใช่แฟรนไชส์"
--   → ชื่อเอกสาร "ใบเสนอแพ็กเกจตัวแทน" (บอสเลือกเอง) — คำที่ทีมใช้ในไฟล์อยู่แล้ว: Proposal · Dealer Package · Standard/Exclusive
--
-- ══════════════════════════════════════════════════════════════════════════
-- กติกาเดียวกับใบเสนอราคาของตัวแทน (0145 · ปิดการขายต้องมีใบที่ส่งแล้ว):
--   สร้างตัวแทนใหม่จากลูกค้าเป้าหมายได้ ต่อเมื่อมีใบของรายนั้นที่ "ส่งแล้ว" หรือ "ตอบรับ" อย่างน้อย 1 ใบ
--   ด่านจริงอยู่ที่ POST /api/admin/dealers (ที่เดียวที่สร้างตัวแทนได้) · หน้าจอกันไว้อีกชั้น
--
-- ด่านในตารางนี้ (บังคับที่ฐานข้อมูล ทุกเส้นทางโดนเหมือนกัน):
--   · เลขที่ใบ DP-ปี-NNNN ฐานข้อมูลออกให้เสมอ — ผู้เรียกกำหนดเองไม่ได้ และแก้ภายหลังไม่ได้
--   · สถานะเดินหน้าได้ทางเดียว: ร่าง → ส่งแล้ว → ตอบรับ / ปฏิเสธ (ข้ามจากร่างไปตอบรับไม่ได้)
--   · ส่งแล้วแก้เนื้อหาไม่ได้ (เปลี่ยนได้แค่สถานะ/หมายเหตุ) และลบไม่ได้ — เป็นหลักฐานว่าเสนออะไรไป
--     (ถ้าแก้ได้ ใบที่ลูกค้าถืออยู่กับที่ระบบเก็บจะไม่ตรงกัน)
--
-- ช่องข้อมูลมีเท่าที่มีที่มาจริง: แพ็กเกจ Standard/Exclusive + เงื่อนไข จากไฟล์ของเบนจามิน
--   มูลค่าแพ็กเกจเป็นช่องให้ HQ กรอกเอง ไม่บังคับ (ไฟล์ยังไม่มีตัวเลขจริง ห้ามเติมให้)
-- ══════════════════════════════════════════════════════════════════════════

-- ตัวนับเลขที่ใบรายปี — แตะได้เฉพาะตัวดักของตารางใบ (security definer) ไม่มีใครอ่าน/เขียนตรง
create table if not exists public.dealer_proposal_counters (
  year    int primary key,
  next_no int not null
);
alter table public.dealer_proposal_counters enable row level security;
revoke all on public.dealer_proposal_counters from public, anon, authenticated;

create table if not exists public.dealer_package_proposals (
  id            bigint generated by default as identity primary key,
  -- ลบลูกค้าเป้าหมาย = ลบใบของรายนั้นตามไปด้วย (ตัวดักด้านล่างยอมให้ลบใบที่ส่งแล้วเฉพาะกรณีนี้)
  prospect_id   bigint not null references public.dealer_prospects(id) on delete cascade,
  proposal_no   text unique,
  package       text not null check (package in ('standard', 'exclusive')),
  region        text,
  province      text,
  amount        numeric check (amount is null or amount >= 0),
  terms         text,
  proposed_date date not null default ((now() at time zone 'Asia/Bangkok')::date),
  valid_until   date,
  status        text not null default 'draft' check (status in ('draft', 'sent', 'accepted', 'rejected')),
  note          text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  constraint dealer_package_proposals_valid_range check (valid_until is null or valid_until >= proposed_date)
);

comment on table public.dealer_package_proposals is
  'ใบเสนอแพ็กเกจตัวแทน (ของสำนักงานใหญ่) — ต้องมีใบที่ส่งแล้ว/ตอบรับ ถึงจะสร้างตัวแทนใหม่จากลูกค้าเป้าหมายได้';

create index if not exists dealer_package_proposals_prospect_idx on public.dealer_package_proposals (prospect_id);

create or replace function public.dealer_package_proposals_before_write() returns trigger
  language plpgsql security definer set search_path = public as $$
declare
  y int;
  n int;
begin
  if tg_op = 'INSERT' then
    -- เลขที่ใบออกที่นี่เสมอ — ไม่รับค่าจากผู้เรียก (กันปลอมเลข/เลขชน)
    y := extract(year from (now() at time zone 'Asia/Bangkok'))::int;
    insert into dealer_proposal_counters(year, next_no) values (y, 2)
      on conflict (year) do update set next_no = dealer_proposal_counters.next_no + 1
      returning next_no - 1 into n;
    new.proposal_no := 'DP-' || y || '-' || lpad(n::text, 4, '0');
  else
    -- ของที่ห้ามเปลี่ยนหลังสร้าง (แอปส่งทั้งแถวกลับมา — ตรึงค่าเดิมไว้ ไม่ต้องพึ่งว่าแอปส่งถูก)
    new.id := old.id;
    new.prospect_id := old.prospect_id;
    new.proposal_no := old.proposal_no;
    new.created_at := old.created_at;

    if new.status is distinct from old.status and not (
         (old.status = 'draft' and new.status = 'sent')
      or (old.status = 'sent'  and new.status in ('accepted', 'rejected'))
    ) then
      raise exception 'proposal_status: เปลี่ยนสถานะใบเสนอแพ็กเกจจาก % เป็น % ไม่ได้', old.status, new.status;
    end if;

    if old.status <> 'draft' and (
         new.package       is distinct from old.package
      or new.region        is distinct from old.region
      or new.province      is distinct from old.province
      or new.amount        is distinct from old.amount
      or new.terms         is distinct from old.terms
      or new.proposed_date is distinct from old.proposed_date
      or new.valid_until   is distinct from old.valid_until
    ) then
      raise exception 'proposal_locked: ใบที่ส่งแล้วแก้เนื้อหาไม่ได้ — เปลี่ยนได้แค่สถานะ';
    end if;
  end if;
  new.updated_at := now();
  return new;
end $$;

drop trigger if exists dealer_package_proposals_before_write on public.dealer_package_proposals;
create trigger dealer_package_proposals_before_write before insert or update on public.dealer_package_proposals
  for each row execute function public.dealer_package_proposals_before_write();

-- ลบได้เฉพาะใบร่าง — ยกเว้นตอนลบลูกค้าเป้าหมายทั้งราย (ลบต่อเนื่องจาก FK = ทำงานในตัวดักชั้นที่ 2)
create or replace function public.dealer_package_proposals_before_delete() returns trigger
  language plpgsql set search_path = public as $$
begin
  if old.status <> 'draft' and pg_trigger_depth() = 1 then
    raise exception 'proposal_locked: ลบได้เฉพาะใบร่าง — ใบที่ส่งแล้วต้องเก็บไว้เป็นหลักฐาน';
  end if;
  return old;
end $$;

drop trigger if exists dealer_package_proposals_before_delete on public.dealer_package_proposals;
create trigger dealer_package_proposals_before_delete before delete on public.dealer_package_proposals
  for each row execute function public.dealer_package_proposals_before_delete();

-- ── สิทธิ์ — ชุดเดียวกับลูกค้าเป้าหมายของสำนักงานใหญ่ (0170) ──
--   อ่าน = ฝั่งสำนักงานใหญ่ · เขียน = ผู้ดูแลข้อมูลกลาง · ตัวแทนจำหน่ายไม่เห็นสักแถว
alter table public.dealer_package_proposals enable row level security;
revoke all on public.dealer_package_proposals from public, anon;
grant select, insert, update, delete on public.dealer_package_proposals to authenticated;

drop policy if exists dealer_package_proposals_read on public.dealer_package_proposals;
create policy dealer_package_proposals_read on public.dealer_package_proposals
  for select using ( is_hq() );

drop policy if exists dealer_package_proposals_write on public.dealer_package_proposals;
create policy dealer_package_proposals_write on public.dealer_package_proposals
  for all using ( can_write_master() ) with check ( can_write_master() );
